In [8]:
import pandas as pd
import pickle
import gzip
import pybaseball

In [4]:
with gzip.open('data_2022_zip.pickle', 'rb') as f:
    data_2022 = pickle.load(f)
with gzip.open('data_2023_zip.pickle', 'rb') as f:
    data_2023 = pickle.load(f)

In [7]:
data_2022['game_date']

191   2022-11-05
204   2022-11-05
206   2022-11-05
222   2022-11-05
225   2022-11-05
         ...
414   2022-03-17
463   2022-03-17
522   2022-03-17
533   2022-03-17
593   2022-03-17
Name: game_date, Length: 773618, dtype: datetime64[ns]

In [17]:
stats_2022 = pybaseball.pitching_stats(2022)
stats_2023 = pybaseball.pitching_stats(2023)
print(set(stats_2022['Name']) - set(stats_2023['Name']))
print(set(stats_2023['Name']) - set(stats_2022['Name']))

{'Shane Bieber', 'Kyle Freeland', 'Jameson Taillon', 'Martin Perez', 'Julio Urias', 'Adam Wainwright', 'Cal Quantrill', 'Alek Manoah', 'Yu Darvish', 'Marco Gonzales', 'Nick Pivetta', 'Triston McKenzie', 'Shohei Ohtani', 'Shane McClanahan', 'Kyle Wright', 'Jose Urquidy', 'Joe Musgrove', 'Corey Kluber', 'Jose Quintana', 'Tyler Anderson', 'Cole Irvin', 'Max Fried', 'German Marquez', 'Carlos Rodon', 'Robbie Ray'}
{'Dane Dunning', 'Jesus Luzardo', 'Luis Castillo', 'Blake Snell', 'Patrick Corbin', 'Cristian Javier', 'Dean Kremer', 'Lucas Giolito', 'Sonny Gray', 'Mitch Keller', 'Freddy Peralta', 'Bryce Elder', 'Kyle Bradish', 'Spencer Strider', 'George Kirby', 'Taijuan Walker', 'Justin Steele', 'JP Sears', 'Yusei Kikuchi', 'Johan Oviedo', 'Kodai Senga', 'Zach Eflin', 'Zack Wheeler', 'Lance Lynn'}

# 볼카운트 초기화 되는 경우 찾기

In [37]:
data_2022['events'].unique()

array(['field_out', 'single', nan, 'strikeout', 'walk', 'home_run',
       'force_out', 'hit_by_pitch', 'grounded_into_double_play',
       'fielders_choice_out', 'double', 'strikeout_double_play',
       'sac_fly', 'field_error', 'sac_bunt_double_play',
       'fielders_choice', 'sac_bunt', 'double_play', 'caught_stealing_2b',
       'triple', 'other_out', 'pickoff_3b', 'catcher_interf',
       'caught_stealing_3b', 'pickoff_caught_stealing_2b', 'triple_play',
       'caught_stealing_home', 'sac_fly_double_play', 'wild_pitch',
       'pickoff_1b', 'pickoff_caught_stealing_home',
       'pickoff_caught_stealing_3b', 'game_advisory', 'pickoff_2b'],
      dtype=object)

In [56]:
data_2022[~data_2022['events'].isna()]['events'].info()

<class 'pandas.core.series.Series'>
Index: 205154 entries, 191 to 522
Series name: events
Non-Null Count   Dtype
--------------   -----
205154 non-null  object
dtypes: object(1)
memory usage: 3.1+ MB

In [81]:
tmp_2022 = data_2022.reset_index(drop=True)
tmp_2023 = data_2023.reset_index(drop=True)

tmp_2022[['balls','strikes']]

        balls  strikes
0           0        0
1           0        0
2           0        0
3           1        2
4           1        1
...       ...      ...
773613      0        1
773614      0        0
773615      0        2
773616      0        1
773617      0        0

[773618 rows x 2 columns]

In [82]:
ind_list

Index([    -1,      0,      1,      2,      6,     10,     17,     21,     25,
           29,
       ...
       773587, 773591, 773594, 773599, 773601, 773604, 773607, 773610, 773611,
       773614],
      dtype='int64', length=205154)

In [83]:
ind_list = tmp_2022[~tmp_2022['events'].isna()].index - 1
filter1_2022 = tmp_2022.iloc[ind_list[1:],:][['events','balls','strikes']]
filter2_2022 = filter1_2022[filter1_2022['events'].isna()]
filter2_2022[(filter2_2022['balls']!=0)&(filter2_2022['strikes']!=0)]

Empty DataFrame
Columns: [events, balls, strikes]
Index: []

In [84]:
ind_list = tmp_2023[~tmp_2023['events'].isna()].index - 1
filter1_2023 = tmp_2023.iloc[ind_list[1:],:][['events','balls','strikes']]
filter2_2023 = filter1_2023[filter1_2023['events'].isna()]
filter2_2023[(filter2_2023['balls']!=0)&(filter2_2023['strikes']!=0)]

Empty DataFrame
Columns: [events, balls, strikes]
Index: []

In [93]:
tmp_2023[(tmp_2023['game_date']=='2023-04-05')&(tmp_2023['player_name'].str.contains('Shohei'))&(tmp_2023['batter']==663728)][['events','balls','strikes']]

           events  balls  strikes
705951  field_out      1        1
705952        NaN      1        0
705953        NaN      0        0
706024  force_out      1        2
706025        NaN      1        1
706026        NaN      1        0
706027        NaN      0        0
706094  strikeout      3        2
706095        NaN      2        2
706096        NaN      2        1
706097        NaN      2        0
706098        NaN      1        0

In [ ]:
ind_list = data_2022[~data_2022['events'].isna()].index

In [ ]:
reset_list = ['hit_into_play', 'foul', 'ball', 'foul_tip', 'swinging_strike',
       'swinging_strike_blocked', 'called_strike', 'foul_bunt',
       'blocked_ball', 'hit_by_pitch', 'missed_bunt', 'pitchout',
       'bunt_foul_tip']

In [26]:
pybaseball.team_pitching(2022)

,teamIDfg,Season,Team,Age,W,L,ERA,G,GS,CG,...,Pit+ FC,Stf+ FS,Loc+ FS,Pit+ FS,Stuff+,Location+,Pitching+,Stf+ FO,Loc+ FO,Pit+ FO
0,22,2022,LAD,29,111,51,2.80,725,162,1,...,104,131.0,102.0,115.0,104,102,103,NaN,NaN,NaN
1,21,2022,HOU,28,106,56,2.90,642,162,3,...,100,116.0,96.0,109.0,111,101,103,NaN,NaN,NaN
2,9,2022,NYY,29,99,63,3.30,669,162,1,...,97,124.0,96.0,110.0,110,100,103,NaN,NaN,NaN
3,12,2022,TBR,28,86,76,3.41,734,162,0,...,99,97.0,100.0,111.0,104,102,103,NaN,NaN,NaN
4,16,2022,ATL,29,101,61,3.46,680,162,1,...,101,94.0,101.0,100.0,102,100,101,NaN,NaN,NaN
5,5,2022,CLE,27,92,70,3.47,669,162,1,...,100,103.0,94.0,99.0,101,100,100,NaN,NaN,NaN
6,25,2022,NYM,30,101,61,3.58,645,162,0,...,101,120.0,102.0,110.0,103,101,102,NaN,NaN,NaN
7,11,2022,SEA,28,90,72,3.59,698,162,0,...,95,128.0,101.0,111.0,101,100,101,NaN,NaN,NaN
8,1,2022,LAA,28,73,89,3.79,652,162,2,...,96,117.0,102.0,110.0,100,99,99,NaN,NaN,NaN
9,28,2022,STL,28,93,69,3.79,628,162,3,...,98,NaN,NaN,NaN,96,100,98,NaN,NaN,NaN
10,29,2022,SDP,29,89,73,3.81,649,162,0,...,99,109.0,106.0,108.0,104,100,102,NaN,NaN,NaN
11,23,2022,MIL,29,86,76,3.83,710,162,0,...,104,81.0,98.0,108.0,103,100,101,NaN,NaN,NaN
12,30,2022,SFG,28,81,81,3.86,738,162,1,...,95,92.0,100.0,104.0,102,101,102,NaN,NaN,NaN
13,20,2022,MIA,28,69,93,3.87,694,162,6,...,96,67.0,94.0,102.0,104,101,101,NaN,NaN,NaN
14,14,2022,TOR,29,92,70,3.89,746,162,0,...,97,116.0,108.0,114.0,103,101,101,NaN,NaN,NaN
15,4,2022,CHW,30,81,81,3.94,711,162,2,...,93,NaN,NaN,NaN,102,99,100,NaN,NaN,NaN
16,2,2022,BAL,27,83,79,3.97,703,162,2,...,101,169.0,100.0,126.0,99,100,100,NaN,NaN,NaN
17,26,2022,PHI,28,87,75,3.98,678,162,3,...,98,84.0,97.0,100.0,99,101,100,NaN,NaN,NaN
18,8,2022,MIN,28,78,84,3.98,710,162,0,...,93,110.0,97.0,102.0,100,101,101,NaN,NaN,NaN
19,17,2022,CHC,29,74,88,4.03,690,162,0,...,97,74.0,98.0,97.0,95,100,98,NaN,NaN,NaN
20,6,2022,DET,28,66,96,4.04,742,162,0,...,97,114.0,98.0,103.0,94,99,97,NaN,NaN,NaN
21,13,2022,TEX,28,68,94,4.22,694,162,1,...,94,77.0,92.0,84.0,95,98,97,NaN,NaN,NaN
22,15,2022,ARI,29,74,88,4.25,708,162,0,...,97,56.0,93.0,93.0,93,101,98,NaN,NaN,NaN
23,3,2022,BOS,29,78,84,4.53,738,162,5,...,99,110.0,99.0,105.0,102,99,100,NaN,NaN,NaN
24,10,2022,OAK,28,60,102,4.54,692,162,0,...,94,106.0,103.0,117.0,90,99,97,NaN,NaN,NaN
25,27,2022,PIT,27,62,100,4.66,666,162,0,...,97,104.0,101.0,110.0,95,99,98,NaN,NaN,NaN
26,7,2022,KCR,27,65,97,4.72,722,162,0,...,99,71.0,92.0,92.0,95,98,97,NaN,NaN,NaN
27,18,2022,CIN,28,62,100,4.86,736,162,1,...,101,91.0,97.0,99.0,100,99,99,NaN,NaN,NaN
28,24,2022,WSN,29,55,107,5.00,750,162,2,...,96,100.0,95.0,103.0,94,99,97,NaN,NaN,NaN
29,19,2022,COL,29,68,94,5.08,659,162,1,...,97,64.0,94.0,84.0,89,98,95,NaN,NaN,NaN

In [12]:
pybaseball.pitching_stats(2023)

,IDfg,Season,Name,Team,Age,W,L,WAR,ERA,G,...,Pit+ FC,Stf+ FS,Loc+ FS,Pit+ FS,Stuff+,Location+,Pitching+,Stf+ FO,Loc+ FO,Pit+ FO
19,10310,2023,Zack Wheeler,PHI,33,13,6,5.9,3.61,32,...,NaN,NaN,NaN,NaN,109,106,111,NaN,NaN,NaN
27,27498,2023,Spencer Strider,ATL,24,20,5,5.5,3.86,32,...,NaN,NaN,NaN,NaN,125,104,112,NaN,NaN,NaN
6,14107,2023,Kevin Gausman,TOR,32,12,9,5.3,3.16,31,...,NaN,105.0,108.0,109.0,105,104,105,NaN,NaN,NaN
2,12768,2023,Sonny Gray,MIN,33,8,8,5.3,2.79,32,...,102.0,NaN,NaN,NaN,103,101,104,NaN,NaN,NaN
15,19291,2023,Zac Gallen,ARI,27,17,9,5.2,3.47,34,...,95.0,NaN,NaN,NaN,106,104,107,NaN,NaN,NaN
1,13125,2023,Gerrit Cole,NYY,32,15,4,5.2,2.63,33,...,102.0,NaN,NaN,NaN,121,104,109,NaN,NaN,NaN
5,17312,2023,Justin Steele,CHC,27,16,5,4.9,3.06,30,...,NaN,NaN,NaN,NaN,99,102,102,NaN,NaN,NaN
9,17995,2023,Logan Webb,SFG,26,11,13,4.9,3.25,33,...,NaN,NaN,NaN,NaN,104,104,103,NaN,NaN,NaN
16,13774,2023,Zach Eflin,TBR,29,16,8,4.8,3.50,31,...,102.0,NaN,NaN,NaN,98,108,106,NaN,NaN,NaN
22,17085,2023,Pablo Lopez,MIN,27,11,8,4.5,3.66,32,...,NaN,NaN,NaN,NaN,99,107,109,NaN,NaN,NaN
12,25436,2023,George Kirby,SEA,25,13,10,4.4,3.35,31,...,NaN,95.0,103.0,110.0,106,110,109,NaN,NaN,NaN
14,17295,2023,Framber Valdez,HOU,29,12,11,4.3,3.45,31,...,108.0,NaN,NaN,NaN,106,98,100,NaN,NaN,NaN
7,16511,2023,Jordan Montgomery,- - -,30,10,11,4.3,3.20,32,...,86.0,NaN,NaN,NaN,97,101,96,NaN,NaN,NaN
0,13543,2023,Blake Snell,SDP,30,14,9,4.1,2.25,32,...,NaN,NaN,NaN,NaN,107,95,100,NaN,NaN,NaN
34,16149,2023,Aaron Nola,PHI,30,12,9,3.9,4.46,32,...,105.0,NaN,NaN,NaN,101,107,106,NaN,NaN,NaN
3,24586,2023,Kyle Bradish,BAL,26,12,7,3.8,2.83,30,...,NaN,NaN,NaN,NaN,126,103,105,NaN,NaN,NaN
17,19959,2023,Jesus Luzardo,MIA,25,10,10,3.7,3.58,32,...,75.0,NaN,NaN,NaN,102,100,101,NaN,NaN,NaN
37,18525,2023,Dylan Cease,CHW,27,7,9,3.7,4.58,33,...,NaN,NaN,NaN,NaN,115,97,104,NaN,NaN,NaN
11,15689,2023,Luis Castillo,SEA,30,14,9,3.4,3.34,33,...,NaN,NaN,NaN,NaN,96,103,102,NaN,NaN,NaN
4,31838,2023,Kodai Senga,NYM,30,12,7,3.4,2.98,29,...,93.0,NaN,NaN,NaN,97,95,97,83.0,94.0,100.0
13,19361,2023,Corbin Burnes,MIL,28,10,8,3.4,3.39,32,...,103.0,NaN,NaN,NaN,127,102,107,NaN,NaN,NaN
8,8700,2023,Justin Verlander,- - -,40,13,8,3.3,3.22,27,...,NaN,NaN,NaN,NaN,106,104,105,NaN,NaN,NaN
31,17594,2023,Mitch Keller,PIT,27,13,9,3.3,4.21,32,...,99.0,NaN,NaN,NaN,104,103,103,NaN,NaN,NaN
24,22250,2023,Logan Gilbert,SEA,26,13,7,3.2,3.73,32,...,NaN,98.0,103.0,117.0,106,102,102,NaN,NaN,NaN
10,11156,2023,Merrill Kelly,ARI,34,12,8,3.2,3.29,30,...,99.0,NaN,NaN,NaN,92,105,103,NaN,NaN,NaN
39,9803,2023,Miles Mikolas,STL,34,9,13,3.1,4.78,35,...,NaN,NaN,NaN,NaN,88,108,102,NaN,NaN,NaN
26,18679,2023,Freddy Peralta,MIL,27,12,10,3.0,3.86,30,...,NaN,NaN,NaN,NaN,103,102,105,NaN,NaN,NaN
21,14168,2023,Jose Berrios,TOR,29,11,12,3.0,3.65,32,...,NaN,NaN,NaN,NaN,100,104,103,NaN,NaN,NaN
30,18684,2023,Sandy Alcantara,MIA,27,7,12,2.9,4.14,28,...,NaN,NaN,NaN,NaN,113,106,108,NaN,NaN,NaN
20,4676,2023,Charlie Morton,ATL,39,14,12,2.7,3.64,30,...,88.0,NaN,NaN,NaN,106,96,98,NaN,NaN,NaN
18,12304,2023,Chris Bassitt,TOR,34,16,8,2.6,3.60,33,...,102.0,83.0,83.0,84.0,92,100,99,NaN,NaN,NaN
38,10123,2023,Kyle Gibson,BAL,35,15,9,2.6,4.73,33,...,92.0,NaN,NaN,NaN,93,100,97,NaN,NaN,NaN
28,20633,2023,Yusei Kikuchi,TOR,32,11,6,2.6,3.86,32,...,NaN,NaN,NaN,NaN,105,101,102,NaN,NaN,NaN
33,11836,2023,Taijuan Walker,PHI,30,15,6,2.5,4.38,31,...,100.0,104.0,97.0,100.0,93,99,97,NaN,NaN,NaN
23,19409,2023,Dane Dunning,TEX,28,12,7,2.1,3.70,35,...,95.0,NaN,NaN,NaN,84,102,96,NaN,NaN,NaN
36,17606,2023,Cristian Javier,HOU,26,10,5,1.9,4.56,31,...,NaN,NaN,NaN,NaN,102,98,100,NaN,NaN,NaN
25,27779,2023,Bryce Elder,ATL,24,12,4,1.8,3.81,31,...,NaN,NaN,NaN,NaN,80,99,95,NaN,NaN,NaN
32,22487,2023,Johan Oviedo,PIT,25,9,14,1.8,4.31,32,...,NaN,NaN,NaN,NaN,91,95,95,NaN,NaN,NaN
29,19350,2023,Dean Kremer,BAL,27,13,5,1.5,4.12,32,...,102.0,NaN,NaN,NaN,99,102,100,NaN,NaN,NaN
40,15474,2023,Lucas Giolito,- - -,28,8,15,1.0,4.88,33,...,NaN,NaN,NaN,NaN,95,101,101,NaN,NaN,NaN
41,9323,2023,Patrick Corbin,WSN,33,10,15,0.9,5.20,32,...,NaN,NaN,NaN,NaN,81,101,95,NaN,NaN,NaN
35,23429,2023,JP Sears,OAK,27,5,14,0.6,4.54,32,...,NaN,NaN,NaN,NaN,93,101,100,NaN,NaN,NaN
42,2520,2023,Lance Lynn,- - -,36,13,11,0.5,5.73,32,...,99.0,NaN,NaN,NaN,94,102,100,NaN,NaN,NaN
43,7593,2023,Jordan Lyles,KCR,32,6,17,0.2,6.28,31,...,98.0,NaN,NaN,NaN,85,101,97,NaN,NaN,NaN